EXECS = matrix 
MPICC = mpicxx
CFLAGS = -03 -std=c++11
//SRC = $(wildcard *.cpp)
//OBJECTS = $(SRC:.cpp=.o)

all: $(EXECS)

//all : ${OBJECTS}

matrix: matrix2.cpp
	${MPICC} ${FLAGS} -o matrix matrix2.cpp
clean:
	rm -f ${EXECS}














